# https://docs.github.com/en/actions/guides/building-and-testing-python#publishing-to-package-registries

name: build & pypi upload

on:
  release:
    types: [ created ]
  workflow_dispatch: # manual execution

jobs:
  pypi-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            container: quay.io/pypa/manylinux_2_24_x86_64  # https://github.com/pypa/manylinux

    container: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      if: matrix.container == ''
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up Python
      if: matrix.container != ''
      run: echo "/opt/python/cp37-cp37m/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Work around arm64 support on MacOS
      # https://github.com/actions/virtual-environments/issues/2557
      if: matrix.os == 'macos-latest'
      run: sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*

    - name: Build source dist
      if: matrix.os == 'ubuntu-latest'
      env:
        TWINE_REPOSITORY: ${{ secrets.PYPI_REPOSITORY }} # used by setup.py
      run: make sdist

    - name: Build binary dist
      env:
        TWINE_REPOSITORY: ${{ secrets.PYPI_REPOSITORY }} # used by setup.py
      run: make bdist

    - name: Upload
      env:
        TWINE_REPOSITORY: ${{ secrets.PYPI_REPOSITORY }}
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
